apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      containers:
        - name: springboot
          image: chthota/employee-api:employee-api
          resources:
            requests:
              memory: "128Mi"
              cpu: "512m"
            limits:
              memory: "128Mi"
              cpu: "512m"

          ports:
            - containerPort: 8090

          env:
            - name: PORT
              value: "8090"
---
apiVersion: v1
kind: Service
metadata:
  name: employee-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8090
  selector:
    app: employee-api